import React, { useState } from 'react';
import { X, Plus, Trash2, FileSpreadsheet, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useApp } from '../../../context/AppContext';
import { JournalLine } from '../../../types';
import { parseRupiahInput, formatRupiah } from '../../../utils/formatters';

interface AddJournalEntryModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const ACCOUNT_CHOICES = [
  { code: '1-1001', name: 'Kas di Tangan' },
  { code: '1-1002', name: 'Bank BCA' },
  { code: '1-1003', name: 'Bank Mandiri' },
  { code: '1-1100', name: 'Piutang Usaha' },
  { code: '2-1001', name: 'Hutang Usaha' },
  { code: '2-1002', name: 'Hutang Pajak PPN' },
  { code: '3-1001', name: 'Modal Disetor' },
  { code: '4-1001', name: 'Pendapatan Penjualan' },
  { code: '5-1001', name: 'Harga Pokok Penjualan (HPP)' },
  { code: '6-1001', name: 'Beban Operasional' },
  { code: '6-1002', name: 'Beban Gaji' },
  { code: '6-1003', name: 'Beban Pemasaran' },
];

export const AddJournalEntryModal: React.FC<AddJournalEntryModalProps> = ({
  isOpen,
  onClose,
}) => {
  const { addJournalEntry, journalEntries } = useApp();

  const [entryNumber, setEntryNumber] = useState(`JU-${new Date().getFullYear()}-${String(journalEntries.length + 1).padStart(4, '0')}`);
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [description, setDescription] = useState('');

  const [lines, setLines] = useState<{
    id: string;
    accountCode: string;
    accountName: string;
    debitStr: string;
    creditStr: string;
  }[]>([
    { id: '1', accountCode: '1-1001', accountName: 'Kas di Tangan', debitStr: '', creditStr: '' },
    { id: '2', accountCode: '4-1001', accountName: 'Pendapatan Penjualan', debitStr: '', creditStr: '' },
  ]);

  if (!isOpen) return null;

  const handleAccountChange = (idx: number, code: string) => {
    const acc = ACCOUNT_CHOICES.find(a => a.code === code);
    setLines(prev => prev.map((l, i) => i === idx ? { ...l, accountCode: code, accountName: acc?.name || '' } : l));
  };

  const handleDebitChange = (idx: number, val: string) => {
    setLines(prev => prev.map((l, i) => i === idx ? { ...l, debitStr: val, creditStr: val ? '' : l.creditStr } : l));
  };

  const handleCreditChange = (idx: number, val: string) => {
    setLines(prev => prev.map((l, i) => i === idx ? { ...l, creditStr: val, debitStr: val ? '' : l.debitStr } : l));
  };

  const addLine = () => {
    setLines(prev => [
      ...prev,
      { id: String(Date.now()), accountCode: '6-1001', accountName: 'Beban Operasional', debitStr: '', creditStr: '' }
    ]);
  };

  const removeLine = (idx: number) => {
    if (lines.length <= 2) return;
    setLines(prev => prev.filter((_, i) => i !== idx));
  };

  const totalDebit = lines.reduce((s, l) => s + (parseRupiahInput(l.debitStr) || 0), 0);
  const totalCredit = lines.reduce((s, l) => s + (parseRupiahInput(l.creditStr) || 0), 0);
  const isBalanced = totalDebit > 0 && totalDebit === totalCredit;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!isBalanced || !description.trim()) return;

    const formattedLines: JournalLine[] = lines.map(l => ({
      id: `line-${Date.now()}-${l.id}`,
      accountCode: l.accountCode,
      accountName: l.accountName,
      debit: parseRupiahInput(l.debitStr) || 0,
      credit: parseRupiahInput(l.creditStr) || 0,
    }));

    addJournalEntry({
      entryNumber,
      date,
      description,
      lines: formattedLines,
      isAutoGenerated: false,
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in">
      <div className="bg-white dark:bg-slate-900 rounded-2xl w-full max-w-lg border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden animate-in zoom-in-95 max-h-[90vh] flex flex-col">
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
              <FileSpreadsheet className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              Buat Jurnal Umum Manual / Penyesuaian
            </h3>
          </div>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-600">
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 space-y-3 text-xs overflow-y-auto flex-1">
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className="text-slate-600 dark:text-slate-300 font-medium mb-1 block">Nomor Bukti Jurnal</label>
              <input
                type="text"
                value={entryNumber}
                onChange={(e) => setEntryNumber(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-mono"
                required
              />
            </div>
            <div>
              <label className="text-slate-600 dark:text-slate-300 font-medium mb-1 block">Tanggal Pembukuan</label>
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white"
                required
              />
            </div>
          </div>

          <div>
            <label className="text-slate-600 dark:text-slate-300 font-medium mb-1 block">Keterangan / Transaksi</label>
            <input
              type="text"
              placeholder="Contoh: Penyesuaian penyusutan aset bulan ini"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white"
              required
            />
          </div>

          {/* Lines */}
          <div className="space-y-2 pt-1">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-800 dark:text-slate-200">Baris Debit & Kredit:</span>
              <button
                type="button"
                onClick={addLine}
                className="text-[11px] font-semibold text-emerald-600 dark:text-emerald-400 flex items-center gap-1 hover:underline"
              >
                <Plus className="w-3 h-3" /> Tambah Baris
              </button>
            </div>

            <div className="space-y-2">
              {lines.map((line, idx) => (
                <div key={line.id} className="p-2.5 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
                  <div className="flex items-center justify-between gap-2">
                    <select
                      value={line.accountCode}
                      onChange={(e) => handleAccountChange(idx, e.target.value)}
                      className="flex-1 px-2.5 py-1.5 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-medium"
                    >
                      {ACCOUNT_CHOICES.map(a => (
                        <option key={a.code} value={a.code}>{a.code} - {a.name}</option>
                      ))}
                    </select>
                    {lines.length > 2 && (
                      <button
                        type="button"
                        onClick={() => removeLine(idx)}
                        className="p-1 text-slate-400 hover:text-rose-500"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="text-[10px] text-slate-400 uppercase font-semibold">Debit (Rp)</label>
                      <input
                        type="text"
                        placeholder="0"
                        value={line.debitStr ? formatRupiah(parseRupiahInput(line.debitStr), false) : ''}
                        onChange={(e) => handleDebitChange(idx, e.target.value)}
                        className="w-full px-2 py-1 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-emerald-600 dark:text-emerald-400 font-bold"
                      />
                    </div>
                    <div>
                      <label className="text-[10px] text-slate-400 uppercase font-semibold">Kredit (Rp)</label>
                      <input
                        type="text"
                        placeholder="0"
                        value={line.creditStr ? formatRupiah(parseRupiahInput(line.creditStr), false) : ''}
                        onChange={(e) => handleCreditChange(idx, e.target.value)}
                        className="w-full px-2 py-1 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-rose-600 dark:text-rose-400 font-bold"
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Balance status */}
          <div className="p-3 bg-slate-100 dark:bg-slate-800 rounded-xl space-y-1">
            <div className="flex justify-between font-bold">
              <span>Total Debit: {formatRupiah(totalDebit)}</span>
              <span>Total Kredit: {formatRupiah(totalCredit)}</span>
            </div>
            <div className={`text-[11px] font-semibold flex items-center gap-1.5 ${
              isBalanced ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'
            }`}>
              {isBalanced ? <CheckCircle2 className="w-3.5 h-3.5" /> : <AlertCircle className="w-3.5 h-3.5" />}
              <span>{isBalanced ? 'Jurnal Seimbang (Balance)' : 'Debit dan Kredit Belum Seimbang'}</span>
            </div>
          </div>

          <div className="pt-2 flex justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium"
            >
              Batal
            </button>
            <button
              type="submit"
              disabled={!isBalanced}
              className={`px-5 py-2 rounded-xl font-bold transition-colors ${
                isBalanced 
                  ? 'bg-emerald-600 hover:bg-emerald-700 text-white cursor-pointer' 
                  : 'bg-slate-300 dark:bg-slate-700 text-slate-500 cursor-not-allowed'
              }`}
            >
              Simpan Jurnal
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
