import React, { useState } from 'react';
import { 
  FileSpreadsheet, 
  Plus, 
  Trash2, 
  Sparkles, 
  CheckCircle2,
  Calendar,
  Layers
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { JournalEntry } from '../../types';
import { formatRupiah, formatDateIndonesian } from '../../utils/formatters';

interface GeneralJournalViewProps {
  startDate: string;
  endDate: string;
  onOpenAddModal: () => void;
}

export const GeneralJournalView: React.FC<GeneralJournalViewProps> = ({
  startDate,
  endDate,
  onOpenAddModal,
}) => {
  const { journalEntries, deleteJournalEntry, transactions, addJournalEntry } = useApp();

  // Filter entries in range
  const filteredEntries = journalEntries.filter(
    e => e.date >= startDate && e.date <= endDate
  );

  // Auto-generate journal entries from recent unjournalized transactions
  const handleAutoGenerateJournals = () => {
    const unjournalized = transactions.filter(t => t.status === 'completed').slice(0, 5);
    let count = 0;

    unjournalized.forEach(t => {
      const existing = journalEntries.find(j => j.description.includes(t.id));
      if (!existing) {
        if (t.type === 'income') {
          addJournalEntry({
            entryNumber: `JU-${new Date().getFullYear()}-${String(journalEntries.length + count + 1).padStart(4, '0')}`,
            date: t.transactionDate,
            description: `[Auto-Gen] ${t.description} (Ref: ${t.id})`,
            lines: [
              {
                id: `line-${Date.now()}-1`,
                accountCode: '1-1001',
                accountName: 'Kas & Rekening Bank Operasional',
                debit: t.amount,
                credit: 0,
              },
              {
                id: `line-${Date.now()}-2`,
                accountCode: '4-1001',
                accountName: `Pendapatan: ${t.category}`,
                debit: 0,
                credit: t.amount,
              },
            ],
            isAutoGenerated: true,
          });
          count++;
        } else {
          addJournalEntry({
            entryNumber: `JU-${new Date().getFullYear()}-${String(journalEntries.length + count + 1).padStart(4, '0')}`,
            date: t.transactionDate,
            description: `[Auto-Gen] ${t.description} (Ref: ${t.id})`,
            lines: [
              {
                id: `line-${Date.now()}-1`,
                accountCode: '6-1001',
                accountName: `Beban Operasional: ${t.category}`,
                debit: t.amount,
                credit: 0,
              },
              {
                id: `line-${Date.now()}-2`,
                accountCode: '1-1001',
                accountName: 'Kas & Rekening Bank Operasional',
                debit: 0,
                credit: t.amount,
              },
            ],
            isAutoGenerated: true,
          });
          count++;
        }
      }
    });
  };

  return (
    <div className="p-4 space-y-4">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-slate-900 p-3.5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
        <div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FileSpreadsheet className="w-4 h-4 text-emerald-500" />
            Jurnal Umum (General Journal)
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Pencatatan double-entry debit dan kredit terintegrasi otomatis
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleAutoGenerateJournals}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-50 hover:bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:hover:bg-emerald-900/50 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800 transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Otomatis Jurnal Transaksi</span>
          </button>

          <button
            onClick={onOpenAddModal}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-600 hover:bg-emerald-700 text-white shadow-xs transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Buat Jurnal Manual</span>
          </button>
        </div>
      </div>

      {/* Journal Entries List */}
      <div className="space-y-3">
        {filteredEntries.length === 0 ? (
          <div className="p-8 text-center bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 text-slate-400 text-xs">
            Belum ada entri jurnal umum pada periode ini. Klik "Otomatis Jurnal Transaksi" atau "Buat Jurnal Manual".
          </div>
        ) : (
          filteredEntries.map((entry) => {
            const totalDebit = entry.lines.reduce((s, l) => s + l.debit, 0);
            const totalCredit = entry.lines.reduce((s, l) => s + l.credit, 0);
            const isBalanced = totalDebit === totalCredit;

            return (
              <div 
                key={entry.id}
                className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-xs hover:border-slate-300 dark:hover:border-slate-700 transition-all"
              >
                {/* Entry Header */}
                <div className="p-3 bg-slate-50 dark:bg-slate-850 border-b border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-2 text-xs">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-slate-900 dark:text-white bg-slate-200 dark:bg-slate-800 px-2 py-0.5 rounded">
                      {entry.entryNumber}
                    </span>
                    <span className="text-slate-500 dark:text-slate-400 flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {formatDateIndonesian(entry.date)}
                    </span>
                    {entry.isAutoGenerated && (
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-blue-100 dark:bg-blue-950/50 text-blue-700 dark:text-blue-300">
                        Otomatis
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-3">
                    <span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full ${
                      isBalanced ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-rose-100 text-rose-800'
                    }`}>
                      {isBalanced ? 'Balance' : 'Tidak Seimbang'}
                    </span>
                    <button
                      onClick={() => deleteJournalEntry(entry.id)}
                      className="text-slate-400 hover:text-rose-500 transition-colors p-1"
                      title="Hapus Jurnal"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

                {/* Entry Description */}
                <div className="px-3 pt-2 pb-1 text-xs text-slate-700 dark:text-slate-300 font-medium">
                  {entry.description}
                </div>

                {/* Journal Lines */}
                <div className="p-3 overflow-x-auto">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="text-[10px] text-slate-400 uppercase tracking-wider border-b border-slate-100 dark:border-slate-800">
                        <th className="pb-1 text-left font-semibold">Kode & Nama Akun</th>
                        <th className="pb-1 text-right font-semibold w-28">Debit (Rp)</th>
                        <th className="pb-1 text-right font-semibold w-28">Kredit (Rp)</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100/60 dark:divide-slate-800/40">
                      {entry.lines.map((line) => (
                        <tr key={line.id} className="py-1.5">
                          <td className={`py-1 ${line.credit > 0 ? 'pl-6 text-slate-600 dark:text-slate-400' : 'font-medium text-slate-900 dark:text-white'}`}>
                            <span className="font-mono text-emerald-600 dark:text-emerald-400 font-semibold">{line.accountCode}</span> - {line.accountName}
                          </td>
                          <td className="py-1 text-right font-semibold text-emerald-600 dark:text-emerald-400">
                            {line.debit > 0 ? formatRupiah(line.debit) : '-'}
                          </td>
                          <td className="py-1 text-right font-semibold text-rose-600 dark:text-rose-400">
                            {line.credit > 0 ? formatRupiah(line.credit) : '-'}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr className="border-t border-slate-200 dark:border-slate-700 font-bold text-slate-800 dark:text-white">
                        <td className="pt-1.5 text-right text-[11px]">Total:</td>
                        <td className="pt-1.5 text-right text-emerald-600 dark:text-emerald-400">{formatRupiah(totalDebit)}</td>
                        <td className="pt-1.5 text-right text-rose-600 dark:text-rose-400">{formatRupiah(totalCredit)}</td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
